from django.core.management.base import BaseCommand
from stemlife.models import LifeEvent

class Command(BaseCommand):
    help = 'Populate the database with comprehensive life events for the STEM life simulation game'

    def handle(self, *args, **options):
        self.stdout.write('Creating comprehensive life events...')
        
        # Clear existing events
        LifeEvent.objects.all().delete()
        
        # Infant events (0-2 years) - More events, natural progression
        infant_events = [
            {
                'title': 'First Steps',
                'description': 'I\'m taking my first steps! This is so exciting and scary at the same time.',
                'stage': 'infant', 'category': 'development', 'min_age': 0, 'max_age': 2, 'frequency': 'once',
                'choice1_text': 'Try to walk with my toys',
                'choice1_science': 5, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 10, 'choice1_intelligence': 5, 'choice1_creativity': 3, 'choice1_logic': 2, 'choice1_social': 0, 'choice1_age_increment': 1,
                'choice2_text': 'Explore naturally on my own',
                'choice2_science': 3, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 5, 'choice2_intelligence': 3, 'choice2_creativity': 5, 'choice2_logic': 1, 'choice2_social': 2, 'choice2_age_increment': 1,
            },
            {
                'title': 'First Words',
                'description': 'I\'m starting to say my first words! I want to communicate with everyone around me.',
                'stage': 'infant', 'category': 'development', 'min_age': 0, 'max_age': 2, 'frequency': 'once',
                'choice1_text': 'Try to say simple words like "mama" and "dada"',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 3, 'choice1_intelligence': 8, 'choice1_creativity': 5, 'choice1_logic': 3, 'choice1_social': 10, 'choice1_age_increment': 1,
                'choice2_text': 'Listen and observe how others talk',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 2, 'choice2_intelligence': 10, 'choice2_creativity': 3, 'choice2_logic': 5, 'choice2_social': 8, 'choice2_age_increment': 1,
            },
            {
                'title': 'Exploring Toys',
                'description': 'I have so many colorful toys to play with! I want to figure out how they work.',
                'stage': 'infant', 'category': 'development', 'min_age': 0, 'max_age': 2, 'frequency': 'common',
                'choice1_text': 'Stack blocks and knock them down',
                'choice1_science': 3, 'choice1_technology': 0, 'choice1_engineering': 8, 'choice1_math': 5, 'choice1_health': 5, 'choice1_intelligence': 8, 'choice1_creativity': 5, 'choice1_logic': 8, 'choice1_social': 0, 'choice1_age_increment': 0.5,
                'choice2_text': 'Press buttons on electronic toys',
                'choice2_science': 0, 'choice2_technology': 8, 'choice2_engineering': 3, 'choice2_math': 0, 'choice2_health': 3, 'choice2_intelligence': 5, 'choice2_creativity': 3, 'choice2_logic': 5, 'choice2_social': 0, 'choice2_age_increment': 0.5,
            },
            {
                'title': 'Music Time',
                'description': 'I hear music playing and I want to move and dance to the rhythm!',
                'stage': 'infant', 'category': 'fun', 'min_age': 0, 'max_age': 2, 'frequency': 'common',
                'choice1_text': 'Dance and move to the music',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 8, 'choice1_intelligence': 3, 'choice1_creativity': 12, 'choice1_logic': 2, 'choice1_social': 8, 'choice1_age_increment': 0,
                'choice2_text': 'Listen quietly and enjoy the sounds',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 3, 'choice2_intelligence': 5, 'choice2_creativity': 8, 'choice2_logic': 3, 'choice2_social': 5, 'choice2_age_increment': 0,
            },
            {
                'title': 'Learning to Crawl',
                'description': 'I want to move around and explore my world! Crawling seems like a good way to get started.',
                'stage': 'infant', 'category': 'development', 'min_age': 0, 'max_age': 2, 'frequency': 'once',
                'choice1_text': 'Practice crawling on soft surfaces',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 12, 'choice1_intelligence': 5, 'choice1_creativity': 3, 'choice1_logic': 3, 'choice1_social': 0, 'choice1_age_increment': 1,
                'choice2_text': 'Try to pull myself up to standing',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 15, 'choice2_intelligence': 8, 'choice2_creativity': 5, 'choice2_logic': 5, 'choice2_social': 0, 'choice2_age_increment': 1,
            },
        ]
        
        # Toddler events (3-5 years)
        toddler_events = [
            {
                'title': 'Learning Colors and Shapes',
                'description': 'I\'m learning about colors and shapes! Everything looks so interesting and colorful.',
                'stage': 'toddler', 'category': 'education', 'min_age': 3, 'max_age': 5, 'frequency': 'once',
                'choice1_text': 'Practice naming colors and shapes',
                'choice1_science': 5, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 8,
                'choice1_health': 0, 'choice1_intelligence': 12, 'choice1_creativity': 8, 'choice1_logic': 10, 'choice1_social': 5, 'choice1_age_increment': 1,
                'choice2_text': 'Sort toys by color and shape',
                'choice2_science': 8, 'choice2_technology': 0, 'choice2_engineering': 5, 'choice2_math': 10,
                'choice2_health': 0, 'choice2_intelligence': 15, 'choice2_creativity': 5, 'choice2_logic': 12, 'choice2_social': 3, 'choice2_age_increment': 1,
            },
            {
                'title': 'Building with Blocks',
                'description': 'I love building tall towers with my blocks! I want to make the biggest tower possible.',
                'stage': 'toddler', 'category': 'engineering', 'min_age': 3, 'max_age': 5, 'frequency': 'common',
                'choice1_text': 'Build the tallest tower I can',
                'choice1_science': 3, 'choice1_technology': 0, 'choice1_engineering': 15, 'choice1_math': 8,
                'choice1_health': 5, 'choice1_intelligence': 10, 'choice1_creativity': 8, 'choice1_logic': 12, 'choice1_social': 0, 'choice1_age_increment': 0.5,
                'choice2_text': 'Create different structures and buildings',
                'choice2_science': 5, 'choice2_technology': 0, 'choice2_engineering': 12, 'choice2_math': 5,
                'choice2_health': 3, 'choice2_intelligence': 8, 'choice2_creativity': 15, 'choice2_logic': 10, 'choice2_social': 0, 'choice2_age_increment': 0.5,
            },
            {
                'title': 'Counting Numbers',
                'description': 'I want to learn to count! Numbers are everywhere and I want to understand them.',
                'stage': 'toddler', 'category': 'education', 'min_age': 3, 'max_age': 5, 'frequency': 'once',
                'choice1_text': 'Count objects around me',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 15,
                'choice1_health': 0, 'choice1_intelligence': 12, 'choice1_creativity': 5, 'choice1_logic': 15, 'choice1_social': 3, 'choice1_age_increment': 1,
                'choice2_text': 'Learn to count to ten',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 18,
                'choice2_health': 0, 'choice2_intelligence': 15, 'choice2_creativity': 3, 'choice2_logic': 18, 'choice2_social': 5, 'choice2_age_increment': 1,
            },
            {
                'title': 'Pet Encounter',
                'description': 'I see a friendly dog at the park! I want to pet it and play with it.',
                'stage': 'toddler', 'category': 'fun', 'min_age': 3, 'max_age': 5, 'frequency': 'common',
                'choice1_text': 'Ask permission and gently pet the dog',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 5, 'choice1_intelligence': 3, 'choice1_creativity': 5, 'choice1_logic': 3, 'choice1_social': 15, 'choice1_age_increment': 0,
                'choice2_text': 'Watch from a distance and wave',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 3, 'choice2_intelligence': 5, 'choice2_creativity': 3, 'choice2_logic': 5, 'choice2_social': 8, 'choice2_age_increment': 0,
            },
            {
                'title': 'Drawing and Coloring',
                'description': 'I want to draw and color! I have so many ideas in my head that I want to put on paper.',
                'stage': 'toddler', 'category': 'creativity', 'min_age': 3, 'max_age': 5, 'frequency': 'common',
                'choice1_text': 'Draw pictures of my family and friends',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 3, 'choice1_intelligence': 8, 'choice1_creativity': 18, 'choice1_logic': 5, 'choice1_social': 12, 'choice1_age_increment': 0.5,
                'choice2_text': 'Experiment with different colors and shapes',
                'choice2_science': 5, 'choice2_technology': 0, 'choice2_engineering': 3, 'choice2_math': 3,
                'choice2_health': 2, 'choice2_intelligence': 10, 'choice2_creativity': 20, 'choice2_logic': 8, 'choice2_social': 5, 'choice2_age_increment': 0.5,
            },
        ]
        
        # Child events (6-12 years) - School years, more STEM but also fun
        child_events = [
            {
                'title': 'School Science Fair',
                'description': 'My school is hosting a science fair and I need to choose a project. I\'m excited to show what I can do!',
                'stage': 'child', 'category': 'education', 'min_age': 6, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Build a volcano experiment',
                'choice1_science': 20, 'choice1_technology': 0, 'choice1_engineering': 10, 'choice1_math': 5,
                'choice1_health': 0, 'choice1_intelligence': 10, 'choice1_creativity': 15, 'choice1_logic': 8, 'choice1_social': 5, 'choice1_age_increment': 0,
                'choice2_text': 'Create a weather observation station',
                'choice2_science': 15, 'choice2_technology': 8, 'choice2_engineering': 5, 'choice2_math': 10,
                'choice2_health': 0, 'choice2_intelligence': 8, 'choice2_creativity': 10, 'choice2_logic': 12, 'choice2_social': 3, 'choice2_age_increment': 0,
                'choice3_text': 'Design a simple machine',
                'choice3_science': 8, 'choice3_technology': 5, 'choice3_engineering': 20, 'choice3_math': 15,
                'choice3_health': 0, 'choice3_intelligence': 8, 'choice3_creativity': 12, 'choice3_logic': 15, 'choice3_social': 0, 'choice3_age_increment': 0,
            },
            {
                'title': 'Computer Time',
                'description': 'I want to spend time on the computer. There are so many things I could learn and do!',
                'stage': 'child', 'category': 'technology', 'min_age': 6, 'max_age': 12, 'frequency': 'multiple',
                'choice1_text': 'Learn basic programming with Scratch',
                'choice1_science': 5, 'choice1_technology': 25, 'choice1_engineering': 8, 'choice1_math': 12,
                'choice1_health': 0, 'choice1_intelligence': 15, 'choice1_creativity': 10, 'choice1_logic': 18, 'choice1_social': 0, 'choice1_age_increment': 0,
                'choice2_text': 'Play educational games',
                'choice2_science': 8, 'choice2_technology': 15, 'choice2_engineering': 3, 'choice2_math': 10,
                'choice2_health': 0, 'choice2_intelligence': 12, 'choice2_creativity': 8, 'choice2_logic': 10, 'choice2_social': 5, 'choice2_age_increment': 0,
                'choice3_text': 'Watch educational videos',
                'choice3_science': 10, 'choice3_technology': 8, 'choice3_engineering': 5, 'choice3_math': 8,
                'choice3_health': 0, 'choice3_intelligence': 10, 'choice3_creativity': 5, 'choice3_logic': 8, 'choice3_social': 3, 'choice3_age_increment': 0,
            },
            {
                'title': 'Sports Team Tryouts',
                'description': 'I want to join a sports team at school. I think it would be fun to play with other kids and learn new skills.',
                'stage': 'child', 'category': 'health', 'min_age': 6, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Try out for the team with confidence',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 20, 'choice1_intelligence': 3, 'choice1_creativity': 2, 'choice1_logic': 3, 'choice1_social': 15, 'choice1_age_increment': 0,
                'choice2_text': 'Start with individual sports first',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 15, 'choice2_intelligence': 2, 'choice2_creativity': 3, 'choice2_logic': 2, 'choice2_social': 8, 'choice2_age_increment': 0,
            },
            {
                'title': 'Birthday Party Planning',
                'description': 'My birthday is coming up and I want to plan my own party! I have so many ideas for themes and activities.',
                'stage': 'child', 'category': 'fun', 'min_age': 6, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Plan a themed party with help',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 0, 'choice1_intelligence': 5, 'choice1_creativity': 20, 'choice1_logic': 8, 'choice1_social': 12, 'choice1_age_increment': 0,
                'choice2_text': 'Organize everything myself',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 0, 'choice2_intelligence': 8, 'choice2_creativity': 15, 'choice2_logic': 12, 'choice2_social': 15, 'choice2_age_increment': 0,
            },
            {
                'title': 'Math Homework Help',
                'description': 'I\'m struggling with my math homework and I need help. I want to understand the concepts better.',
                'stage': 'child', 'category': 'education', 'min_age': 6, 'max_age': 12, 'frequency': 'multiple',
                'choice1_text': 'Ask for step-by-step explanations',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 25,
                'choice1_health': 0, 'choice1_intelligence': 15, 'choice1_creativity': 5, 'choice1_logic': 20, 'choice1_social': 5, 'choice1_age_increment': 0,
                'choice2_text': 'Use real-world examples to understand',
                'choice2_science': 5, 'choice2_technology': 0, 'choice2_engineering': 5, 'choice2_math': 20,
                'choice2_health': 0, 'choice2_intelligence': 12, 'choice2_creativity': 8, 'choice2_logic': 18, 'choice2_social': 3, 'choice2_age_increment': 0,
            },
            {
                'title': 'Summer Camp Decision',
                'description': 'I want to go to summer camp! There are several options available and I need to choose which one interests me most.',
                'stage': 'child', 'category': 'adventure', 'min_age': 6, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Choose a STEM-focused science camp',
                'choice1_science': 25, 'choice1_technology': 15, 'choice1_engineering': 15, 'choice1_math': 20,
                'choice1_health': 10, 'choice1_intelligence': 20, 'choice1_creativity': 15, 'choice1_logic': 18, 'choice1_social': 10, 'choice1_age_increment': 0,
                'choice2_text': 'Go to a traditional outdoor adventure camp',
                'choice2_science': 8, 'choice2_technology': 0, 'choice2_engineering': 5, 'choice2_math': 3,
                'choice2_health': 25, 'choice2_intelligence': 8, 'choice2_creativity': 12, 'choice2_logic': 8, 'choice2_social': 20, 'choice2_age_increment': 0,
                'choice3_text': 'Join an arts and crafts camp',
                'choice3_science': 3, 'choice3_technology': 0, 'choice3_engineering': 3, 'choice3_math': 2,
                'choice3_health': 8, 'choice3_intelligence': 8, 'choice3_creativity': 25, 'choice3_logic': 5, 'choice3_social': 15, 'choice3_age_increment': 0,
            },
            {
                'title': 'Learning to Ride a Bike',
                'description': 'I want to learn how to ride a bike! I see other kids riding around and it looks like so much fun.',
                'stage': 'child', 'category': 'health', 'min_age': 6, 'max_age': 10, 'frequency': 'once',
                'choice1_text': 'Practice with training wheels first',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 5, 'choice1_math': 0,
                'choice1_health': 15, 'choice1_intelligence': 8, 'choice1_creativity': 5, 'choice1_logic': 10, 'choice1_social': 8, 'choice1_age_increment': 1,
                'choice2_text': 'Try to ride without training wheels',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 8, 'choice2_math': 0,
                'choice2_health': 20, 'choice2_intelligence': 10, 'choice2_creativity': 8, 'choice2_logic': 12, 'choice2_social': 5, 'choice2_age_increment': 1,
            },
            {
                'title': 'Music Lessons',
                'description': 'I want to learn to play a musical instrument! I think it would be fun to make my own music.',
                'stage': 'child', 'category': 'hobby', 'min_age': 7, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Take piano lessons',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 8,
                'choice1_health': 5, 'choice1_intelligence': 12, 'choice1_creativity': 20, 'choice1_logic': 15, 'choice1_social': 8, 'choice1_age_increment': 1,
                'choice2_text': 'Learn to play guitar',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 5,
                'choice2_health': 8, 'choice2_intelligence': 10, 'choice2_creativity': 18, 'choice2_logic': 12, 'choice2_social': 12, 'choice2_age_increment': 1,
                'choice3_text': 'Join the school band',
                'choice3_science': 0, 'choice3_technology': 0, 'choice3_engineering': 0, 'choice3_math': 3,
                'choice3_health': 5, 'choice3_intelligence': 8, 'choice3_creativity': 15, 'choice3_logic': 8, 'choice3_social': 20, 'choice3_age_increment': 1,
            },
            {
                'title': 'Getting a Pet',
                'description': 'I really want a pet! I think it would be fun to have a furry friend to play with and take care of.',
                'stage': 'child', 'category': 'family', 'min_age': 8, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Ask for a dog and promise to take care of it',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 10, 'choice1_intelligence': 5, 'choice1_creativity': 8, 'choice1_logic': 8, 'choice1_social': 20, 'choice1_age_increment': 1,
                'choice2_text': 'Start with a smaller pet like a hamster',
                'choice2_science': 5, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 5, 'choice2_intelligence': 8, 'choice2_creativity': 5, 'choice2_logic': 10, 'choice2_social': 15, 'choice2_age_increment': 1,
            },
            {
                'title': 'Science Fair Project',
                'description': 'My school is having a science fair and I want to participate! I have so many ideas for experiments.',
                'stage': 'child', 'category': 'education', 'min_age': 8, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Create a volcano eruption experiment',
                'choice1_science': 25, 'choice1_technology': 0, 'choice1_engineering': 10, 'choice1_math': 8,
                'choice1_health': 0, 'choice1_intelligence': 15, 'choice1_creativity': 12, 'choice1_logic': 15, 'choice1_social': 8, 'choice1_age_increment': 1,
                'choice2_text': 'Study plant growth under different conditions',
                'choice2_science': 30, 'choice2_technology': 0, 'choice2_engineering': 5, 'choice2_math': 5,
                'choice2_health': 0, 'choice2_intelligence': 12, 'choice2_creativity': 8, 'choice2_logic': 12, 'choice2_social': 5, 'choice2_age_increment': 1,
            },
            {
                'title': 'Computer Programming Class',
                'description': 'I want to learn how to program computers! I think it would be cool to make my own games and apps.',
                'stage': 'child', 'category': 'technology', 'min_age': 9, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Start with simple programming languages like Scratch',
                'choice1_science': 5, 'choice1_technology': 25, 'choice1_engineering': 8, 'choice1_math': 15,
                'choice1_health': 0, 'choice1_intelligence': 18, 'choice1_creativity': 15, 'choice1_logic': 20, 'choice1_social': 5, 'choice1_age_increment': 1,
                'choice2_text': 'Learn Python programming basics',
                'choice2_science': 8, 'choice2_technology': 30, 'choice2_engineering': 10, 'choice2_math': 20,
                'choice2_health': 0, 'choice2_intelligence': 20, 'choice2_creativity': 12, 'choice2_logic': 25, 'choice2_social': 3, 'choice2_age_increment': 1,
            },
            {
                'title': 'Math Competition',
                'description': 'I\'ve been invited to participate in a math competition! I\'m excited to test my skills against other students.',
                'stage': 'child', 'category': 'education', 'min_age': 10, 'max_age': 12, 'frequency': 'once',
                'choice1_text': 'Practice advanced math problems and strategies',
                'choice1_science': 8, 'choice1_technology': 0, 'choice1_engineering': 5, 'choice1_math': 30,
                'choice1_health': 0, 'choice1_intelligence': 20, 'choice1_creativity': 8, 'choice1_logic': 25, 'choice1_social': 5, 'choice1_age_increment': 1,
                'choice2_text': 'Focus on understanding concepts rather than speed',
                'choice2_science': 5, 'choice2_technology': 0, 'choice2_engineering': 3, 'choice2_math': 25,
                'choice2_health': 0, 'choice2_intelligence': 18, 'choice2_creativity': 5, 'choice2_logic': 20, 'choice2_social': 8, 'choice2_age_increment': 1,
            },
        ]
        
        # Teen events (13-19 years)
        teen_events = [
            {
                'title': 'High School Electives',
                'description': 'It\'s time to choose my high school electives. Which subjects interest me most? I want to pick classes that will help me in the future.',
                'stage': 'teen', 'category': 'education', 'min_age': 13, 'max_age': 19, 'frequency': 'once',
                'choice1_text': 'Take Advanced Mathematics and Physics',
                'choice1_science': 15, 'choice1_technology': 8, 'choice1_engineering': 10, 'choice1_math': 25,
                'choice1_health': 0, 'choice1_intelligence': 15, 'choice1_creativity': 5, 'choice1_logic': 20, 'choice1_social': 0, 'choice1_age_increment': 1,
                'choice2_text': 'Study Computer Science and Programming',
                'choice2_science': 8, 'choice2_technology': 30, 'choice2_engineering': 15, 'choice2_math': 18,
                'choice2_health': 0, 'choice2_intelligence': 18, 'choice2_creativity': 12, 'choice2_logic': 20, 'choice2_social': 5, 'choice2_age_increment': 1,
                'choice3_text': 'Focus on Biology and Chemistry',
                'choice3_science': 25, 'choice3_technology': 5, 'choice3_engineering': 8, 'choice3_math': 12,
                'choice3_health': 8, 'choice3_intelligence': 15, 'choice3_creativity': 10, 'choice3_logic': 12, 'choice3_social': 3, 'choice3_age_increment': 1,
            },
            {
                'title': 'First Date',
                'description': 'I\'ve been asked out on my first date! I\'m excited but also nervous about what to do and how to act.',
                'stage': 'teen', 'category': 'social', 'min_age': 13, 'max_age': 19, 'frequency': 'once',
                'choice1_text': 'Go to a movie and dinner',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 5, 'choice1_intelligence': 3, 'choice1_creativity': 5, 'choice1_logic': 3, 'choice1_social': 20, 'choice1_age_increment': 1,
                'choice2_text': 'Do something active like bowling or mini-golf',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 15, 'choice2_intelligence': 5, 'choice2_creativity': 8, 'choice2_logic': 5, 'choice2_social': 18, 'choice2_age_increment': 1,
            },
            {
                'title': 'Part-Time Job',
                'description': 'I want to get a part-time job to earn some money and gain work experience. What kind of job should I look for?',
                'stage': 'teen', 'category': 'career', 'min_age': 15, 'max_age': 19, 'frequency': 'once',
                'choice1_text': 'Work at a local store or restaurant',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 5,
                'choice1_health': 8, 'choice1_intelligence': 8, 'choice1_creativity': 5, 'choice1_logic': 10, 'choice1_social': 20, 'choice1_age_increment': 1,
                'choice2_text': 'Find a job related to my interests (STEM, arts, etc.)',
                'choice2_science': 10, 'choice2_technology': 10, 'choice2_engineering': 10, 'choice2_math': 8,
                'choice2_health': 5, 'choice2_intelligence': 12, 'choice2_creativity': 8, 'choice2_logic': 12, 'choice2_social': 15, 'choice2_age_increment': 1,
            },
            {
                'title': 'High School Graduation',
                'description': 'Congratulations! I\'ve graduated from high school. This is such a big milestone and I\'m excited about what\'s next for me.',
                'stage': 'teen', 'category': 'education', 'min_age': 17, 'max_age': 19, 'frequency': 'once',
                'choice1_text': 'Go to college for STEM studies',
                'choice1_science': 20, 'choice1_technology': 20, 'choice1_engineering': 20, 'choice1_math': 20,
                'choice1_health': 0, 'choice1_intelligence': 25, 'choice1_creativity': 15, 'choice1_logic': 25, 'choice1_social': 10, 'choice1_age_increment': 2,
                'choice2_text': 'Take a gap year to explore and travel',
                'choice2_science': 10, 'choice2_technology': 5, 'choice2_engineering': 5, 'choice2_math': 5,
                'choice2_health': 10, 'choice2_intelligence': 15, 'choice2_creativity': 20, 'choice2_logic': 10, 'choice2_social': 25, 'choice2_age_increment': 1,
                'choice3_text': 'Start working and save money for the future',
                'choice3_science': 5, 'choice3_technology': 10, 'choice3_engineering': 5, 'choice3_math': 5,
                'choice3_health': 5, 'choice3_intelligence': 10, 'choice3_creativity': 10, 'choice3_logic': 15, 'choice3_social': 20, 'choice3_age_increment': 1,
            },
            {
                'title': 'School Dance',
                'description': 'There\'s a school dance coming up and I\'m not sure if I should go. I\'m nervous about dancing and socializing.',
                'stage': 'teen', 'category': 'social', 'min_age': 13, 'max_age': 19, 'frequency': 'once',
                'choice1_text': 'Go to the dance and have fun',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 5, 'choice1_intelligence': 3, 'choice1_creativity': 8, 'choice1_logic': 3, 'choice1_social': 20, 'choice1_age_increment': 0,
                'choice2_text': 'Stay home and avoid the social pressure',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 0, 'choice2_intelligence': 5, 'choice2_creativity': 3, 'choice2_logic': 5, 'choice2_social': 5, 'choice2_age_increment': 0,
            },
            {
                'title': 'Learning to Cook',
                'description': 'I want to learn how to cook! I think it would be fun to make my own meals and maybe impress my family.',
                'stage': 'teen', 'category': 'hobby', 'min_age': 13, 'max_age': 19, 'frequency': 'once',
                'choice1_text': 'Follow recipes and learn basic techniques',
                'choice1_science': 5, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 8,
                'choice1_health': 8, 'choice1_intelligence': 8, 'choice1_creativity': 10, 'choice1_logic': 12, 'choice1_social': 5, 'choice1_age_increment': 0,
                'choice2_text': 'Experiment and create my own recipes',
                'choice2_science': 8, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 5,
                'choice2_health': 5, 'choice2_intelligence': 10, 'choice2_creativity': 15, 'choice2_logic': 8, 'choice2_social': 3, 'choice2_age_increment': 0,
            },
        ]
        
        # Young Adult events (20-29 years)
        young_adult_events = [
            {
                'title': 'College Major Decision',
                'description': 'I need to choose my college major. This decision will shape my career path and I want to make the right choice.',
                'stage': 'young_adult', 'category': 'education', 'min_age': 18, 'max_age': 22, 'frequency': 'once',
                'choice1_text': 'Choose Computer Science',
                'choice1_science': 10, 'choice1_technology': 30, 'choice1_engineering': 15, 'choice1_math': 20,
                'choice1_health': 0, 'choice1_intelligence': 20, 'choice1_creativity': 10, 'choice1_logic': 25, 'choice1_social': 5, 'choice1_age_increment': 0,
                'choice2_text': 'Choose Mechanical Engineering',
                'choice2_science': 15, 'choice2_technology': 10, 'choice2_engineering': 30, 'choice2_math': 25,
                'choice2_health': 0, 'choice2_intelligence': 18, 'choice2_creativity': 12, 'choice2_logic': 25, 'choice2_social': 3, 'choice2_age_increment': 0,
                'choice3_text': 'Choose Biology',
                'choice3_science': 30, 'choice3_technology': 5, 'choice3_engineering': 8, 'choice3_math': 15,
                'choice3_health': 10, 'choice3_intelligence': 20, 'choice3_creativity': 15, 'choice3_logic': 18, 'choice3_social': 5, 'choice3_age_increment': 0,
            },
            {
                'title': 'First Apartment',
                'description': 'I\'m moving into my first apartment! This is exciting but also overwhelming - I need to figure out how to manage everything on my own.',
                'stage': 'young_adult', 'category': 'development', 'min_age': 20, 'max_age': 25, 'frequency': 'once',
                'choice1_text': 'Plan everything carefully and budget wisely',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 15,
                'choice1_health': 5, 'choice1_intelligence': 15, 'choice1_creativity': 8, 'choice1_logic': 20, 'choice1_social': 8, 'choice1_age_increment': 0,
                'choice2_text': 'Go with the flow and figure it out as I go',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 5,
                'choice2_health': 3, 'choice2_intelligence': 10, 'choice2_creativity': 15, 'choice2_logic': 8, 'choice2_social': 15, 'choice2_age_increment': 0,
            },
            {
                'title': 'First Real Job',
                'description': 'I\'ve been offered my first real job in my field! I\'m excited but nervous about starting my career.',
                'stage': 'young_adult', 'category': 'career', 'min_age': 22, 'max_age': 26, 'frequency': 'once',
                'choice1_text': 'Accept the job and work hard to succeed',
                'choice1_science': 5, 'choice1_technology': 10, 'choice1_engineering': 10, 'choice1_math': 8,
                'choice1_health': 5, 'choice1_intelligence': 15, 'choice1_creativity': 8, 'choice1_logic': 18, 'choice1_social': 15, 'choice1_age_increment': 0,
                'choice2_text': 'Negotiate for better terms before accepting',
                'choice2_science': 3, 'choice2_technology': 5, 'choice2_engineering': 5, 'choice2_math': 10,
                'choice2_health': 3, 'choice2_intelligence': 12, 'choice2_creativity': 10, 'choice2_logic': 20, 'choice2_social': 20, 'choice2_age_increment': 0,
            },
            {
                'title': 'Travel Adventure',
                'description': 'I have the opportunity to travel abroad! This would be my first big international trip and I\'m excited about the adventure.',
                'stage': 'young_adult', 'category': 'adventure', 'min_age': 20, 'max_age': 28, 'frequency': 'once',
                'choice1_text': 'Plan a structured trip with organized tours',
                'choice1_science': 5, 'choice1_technology': 8, 'choice1_engineering': 5, 'choice1_math': 8,
                'choice1_health': 8, 'choice1_intelligence': 12, 'choice1_creativity': 10, 'choice1_logic': 15, 'choice1_social': 15, 'choice1_age_increment': 0,
                'choice2_text': 'Go backpacking and explore freely',
                'choice2_science': 8, 'choice2_technology': 3, 'choice2_engineering': 3, 'choice2_math': 5,
                'choice2_health': 15, 'choice2_intelligence': 15, 'choice2_creativity': 20, 'choice2_logic': 12, 'choice2_social': 25, 'choice2_age_increment': 0,
            },
            {
                'title': 'Relationship Decision',
                'description': 'I\'ve been dating someone for a while and I need to decide if this relationship is going somewhere serious.',
                'stage': 'young_adult', 'category': 'social', 'min_age': 20, 'max_age': 28, 'frequency': 'once',
                'choice1_text': 'Have an honest conversation about the future',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 5, 'choice1_intelligence': 10, 'choice1_creativity': 5, 'choice1_logic': 15, 'choice1_social': 25, 'choice1_age_increment': 0,
                'choice2_text': 'Take more time to figure out my feelings',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 3, 'choice2_intelligence': 8, 'choice2_creativity': 10, 'choice2_logic': 12, 'choice2_social': 18, 'choice2_age_increment': 0,
            },
        ]
        
        # Adult events (30+ years)
        adult_events = [
            {
                'title': 'Career Advancement',
                'description': 'I have the opportunity for a promotion at work. This would mean more responsibility and better pay, but also more stress.',
                'stage': 'adult', 'category': 'career', 'min_age': 30, 'max_age': 50, 'frequency': 'once',
                'choice1_text': 'Take the promotion and work hard to succeed',
                'choice1_science': 8, 'choice1_technology': 10, 'choice1_engineering': 12, 'choice1_math': 10,
                'choice1_health': 5, 'choice1_intelligence': 15, 'choice1_creativity': 8, 'choice1_logic': 20, 'choice1_social': 15, 'choice1_age_increment': 0,
                'choice2_text': 'Stay in current position and focus on work-life balance',
                'choice2_science': 3, 'choice2_technology': 5, 'choice2_engineering': 5, 'choice2_math': 5,
                'choice2_health': 15, 'choice2_intelligence': 8, 'choice2_creativity': 10, 'choice2_logic': 12, 'choice2_social': 20, 'choice2_age_increment': 0,
            },
            {
                'title': 'Starting a Family',
                'description': 'I\'m thinking about starting a family. This is a big decision that will change my life forever.',
                'stage': 'adult', 'category': 'family', 'min_age': 25, 'max_age': 40, 'frequency': 'once',
                'choice1_text': 'Start planning for a family and prepare financially',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 10,
                'choice1_health': 8, 'choice1_intelligence': 12, 'choice1_creativity': 5, 'choice1_logic': 15, 'choice1_social': 25, 'choice1_age_increment': 0,
                'choice2_text': 'Focus on career and personal goals for now',
                'choice2_science': 5, 'choice2_technology': 5, 'choice2_engineering': 5, 'choice2_math': 5,
                'choice2_health': 5, 'choice2_intelligence': 10, 'choice2_creativity': 8, 'choice2_logic': 12, 'choice2_social': 15, 'choice2_age_increment': 0,
            },
            {
                'title': 'Midlife Crisis',
                'description': 'I\'m feeling restless and questioning my life choices. Maybe it\'s time for a change or a new adventure.',
                'stage': 'adult', 'category': 'development', 'min_age': 35, 'max_age': 50, 'frequency': 'once',
                'choice1_text': 'Make a big change - new career or move',
                'choice1_science': 10, 'choice1_technology': 15, 'choice1_engineering': 12, 'choice1_math': 8,
                'choice1_health': 8, 'choice1_intelligence': 18, 'choice1_creativity': 20, 'choice1_logic': 15, 'choice1_social': 15, 'choice1_age_increment': 0,
                'choice2_text': 'Focus on personal growth and hobbies',
                'choice2_science': 5, 'choice2_technology': 5, 'choice2_engineering': 5, 'choice2_math': 5,
                'choice2_health': 15, 'choice2_intelligence': 12, 'choice2_creativity': 18, 'choice2_logic': 10, 'choice2_social': 20, 'choice2_age_increment': 0,
            },
            {
                'title': 'Mentoring Others',
                'description': 'I have the opportunity to mentor younger people in my field. This could be rewarding and help others succeed.',
                'stage': 'adult', 'category': 'career', 'min_age': 30, 'max_age': 60, 'frequency': 'once',
                'choice1_text': 'Become a mentor and share my knowledge',
                'choice1_science': 5, 'choice1_technology': 8, 'choice1_engineering': 8, 'choice1_math': 5,
                'choice1_health': 5, 'choice1_intelligence': 15, 'choice1_creativity': 8, 'choice1_logic': 18, 'choice1_social': 25, 'choice1_age_increment': 0,
                'choice2_text': 'Focus on my own work and development',
                'choice2_science': 8, 'choice2_technology': 10, 'choice2_engineering': 10, 'choice2_math': 8,
                'choice2_health': 3, 'choice2_intelligence': 12, 'choice2_creativity': 10, 'choice2_logic': 15, 'choice2_social': 8, 'choice2_age_increment': 0,
            },
        ]
        
        # Milestone events (trigger age progression)
        milestone_events = [
            {
                'title': 'Starting School',
                'description': 'It\'s my first day of kindergarten! I\'m excited but a little nervous about meeting new friends and learning new things.',
                'stage': 'child', 'category': 'education', 'min_age': 5, 'max_age': 6, 'frequency': 'once',
                'choice1_text': 'Be brave and make new friends',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 0,
                'choice1_health': 5, 'choice1_intelligence': 5, 'choice1_creativity': 8, 'choice1_logic': 5, 'choice1_social': 20, 'choice1_age_increment': 2,
                'choice2_text': 'Stick close to the teacher',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 0,
                'choice2_health': 3, 'choice2_intelligence': 8, 'choice2_creativity': 5, 'choice2_logic': 8, 'choice2_social': 10, 'choice2_age_increment': 2,
            },
            {
                'title': 'Becoming a Teenager',
                'description': 'I\'m turning 13! I\'m officially a teenager now. I feel more grown up and I want to make my own decisions.',
                'stage': 'teen', 'category': 'development', 'min_age': 12, 'max_age': 13, 'frequency': 'once',
                'choice1_text': 'Embrace my independence and make responsible choices',
                'choice1_science': 5, 'choice1_technology': 5, 'choice1_engineering': 5, 'choice1_math': 5,
                'choice1_health': 8, 'choice1_intelligence': 15, 'choice1_creativity': 10, 'choice1_logic': 15, 'choice1_social': 20, 'choice1_age_increment': 3,
                'choice2_text': 'Stay close to family while exploring new interests',
                'choice2_science': 3, 'choice2_technology': 3, 'choice2_engineering': 3, 'choice2_math': 3,
                'choice2_health': 10, 'choice2_intelligence': 12, 'choice2_creativity': 8, 'choice2_logic': 12, 'choice2_social': 15, 'choice2_age_increment': 3,
            },
            {
                'title': 'Learning to Drive',
                'description': 'I\'m old enough to learn to drive! This is a big responsibility and I want to be a safe driver.',
                'stage': 'teen', 'category': 'development', 'min_age': 15, 'max_age': 17, 'frequency': 'once',
                'choice1_text': 'Take driving lessons and practice regularly',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 8, 'choice1_math': 5,
                'choice1_health': 5, 'choice1_intelligence': 10, 'choice1_creativity': 3, 'choice1_logic': 15, 'choice1_social': 8, 'choice1_age_increment': 2,
                'choice2_text': 'Wait until I feel more confident and mature',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 3, 'choice2_math': 3,
                'choice2_health': 8, 'choice2_intelligence': 8, 'choice2_creativity': 5, 'choice2_logic': 10, 'choice2_social': 5, 'choice2_age_increment': 1,
            },
            {
                'title': 'High School Graduation',
                'description': 'I\'m graduating from high school! This is a huge milestone and I\'m excited about what comes next.',
                'stage': 'teen', 'category': 'education', 'min_age': 17, 'max_age': 19, 'frequency': 'once',
                'choice1_text': 'Plan to go to college and study STEM subjects',
                'choice1_science': 20, 'choice1_technology': 15, 'choice1_engineering': 15, 'choice1_math': 20,
                'choice1_health': 5, 'choice1_intelligence': 20, 'choice1_creativity': 10, 'choice1_logic': 20, 'choice1_social': 10, 'choice1_age_increment': 3,
                'choice2_text': 'Take a gap year to explore different career paths',
                'choice2_science': 10, 'choice2_technology': 8, 'choice2_engineering': 8, 'choice2_math': 10,
                'choice2_health': 10, 'choice2_intelligence': 15, 'choice2_creativity': 15, 'choice2_logic': 15, 'choice2_social': 20, 'choice2_age_increment': 2,
                'choice3_text': 'Start working and gain real-world experience',
                'choice3_science': 5, 'choice3_technology': 5, 'choice3_engineering': 5, 'choice3_math': 5,
                'choice3_health': 8, 'choice3_intelligence': 10, 'choice3_creativity': 8, 'choice3_logic': 12, 'choice3_social': 25, 'choice3_age_increment': 2,
            },
            {
                'title': 'Moving Out',
                'description': 'I\'m moving out of my parents\' house and getting my own place! This is exciting but also a bit scary.',
                'stage': 'young_adult', 'category': 'development', 'min_age': 18, 'max_age': 25, 'frequency': 'once',
                'choice1_text': 'Get an apartment with roommates to share expenses',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 8,
                'choice1_health': 5, 'choice1_intelligence': 8, 'choice1_creativity': 5, 'choice1_logic': 10, 'choice1_social': 20, 'choice1_age_increment': 2,
                'choice2_text': 'Find my own small apartment and live independently',
                'choice2_science': 0, 'choice2_technology': 0, 'choice2_engineering': 0, 'choice2_math': 5,
                'choice2_health': 3, 'choice2_intelligence': 10, 'choice2_creativity': 8, 'choice2_logic': 12, 'choice2_social': 15, 'choice2_age_increment': 2,
            },
            {
                'title': 'First Real Job',
                'description': 'I\'ve been offered my first real job in my field! This is a great opportunity to start my career.',
                'stage': 'young_adult', 'category': 'career', 'min_age': 20, 'max_age': 28, 'frequency': 'once',
                'choice1_text': 'Accept the job and work hard to advance quickly',
                'choice1_science': 10, 'choice1_technology': 15, 'choice1_engineering': 15, 'choice1_math': 10,
                'choice1_health': 5, 'choice1_intelligence': 15, 'choice1_creativity': 8, 'choice1_logic': 18, 'choice1_social': 15, 'choice1_age_increment': 2,
                'choice2_text': 'Negotiate for better pay and benefits',
                'choice2_science': 5, 'choice2_technology': 8, 'choice2_engineering': 8, 'choice2_math': 8,
                'choice2_health': 3, 'choice2_intelligence': 12, 'choice2_creativity': 5, 'choice2_logic': 15, 'choice2_social': 20, 'choice2_age_increment': 2,
            },
            {
                'title': 'Starting a Family',
                'description': 'I\'m thinking about starting a family. This is a big decision that will change my life forever.',
                'stage': 'adult', 'category': 'family', 'min_age': 25, 'max_age': 40, 'frequency': 'once',
                'choice1_text': 'Start planning for a family and prepare financially',
                'choice1_science': 0, 'choice1_technology': 0, 'choice1_engineering': 0, 'choice1_math': 10,
                'choice1_health': 8, 'choice1_intelligence': 12, 'choice1_creativity': 5, 'choice1_logic': 15, 'choice1_social': 25, 'choice1_age_increment': 0,
                'choice2_text': 'Focus on career and personal goals for now',
                'choice2_science': 5, 'choice2_technology': 5, 'choice2_engineering': 5, 'choice2_math': 5,
                'choice2_health': 5, 'choice2_intelligence': 10, 'choice2_creativity': 8, 'choice2_logic': 12, 'choice2_social': 15, 'choice2_age_increment': 0,
            },
        ]
        
        # Combine all events
        all_events = infant_events + toddler_events + child_events + teen_events + young_adult_events + adult_events + milestone_events
        
        # Create events in database
        created_events = []
        for event_data in all_events:
            event = LifeEvent.objects.create(**event_data)
            created_events.append(event)
        
        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully created {len(created_events)} life events!'
            )
        )
        
        # Show breakdown by stage
        for stage in ['infant', 'toddler', 'child', 'teen', 'young_adult', 'adult']:
            count = LifeEvent.objects.filter(stage=stage).count()
            self.stdout.write(f'{stage.title()}: {count} events') 