# Generated by Django 5.0.1 on 2024-01-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='Player',
        ),
    ]
