# Generated by Django 5.0.1 on 2024-01-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0003_questions_rename_group_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='age',
            field=models.CharField(default=10, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer3',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer4',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(default='General', max_length=256),
            preserve_default=False,
        ),
    ]
