# Generated by Django 5.0.1 on 2024-01-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0003_questions_rename_group_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='age',
            field=models.CharField(default=10, max_length=250),
            preserve_default=False,
        ),
    ]
