# Generated by Django 5.0.1 on 2024-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0004_questions_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
