# Generated by Django 5.0.1 on 2024-01-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0005_alter_questions_answer3_alter_questions_answer4'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='engineering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='mathematics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='science',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='technology',
            field=models.IntegerField(default=0),
        ),
    ]
