# Generated by Django 5.0.1 on 2024-01-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0005_questions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer3',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer4',
            field=models.CharField(default='', max_length=256),
        ),
    ]
