# Generated by Django 5.0.1 on 2024-01-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0007_alter_questions_answer3_alter_questions_answer4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer3',
            field=models.CharField(blank='True', default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer4',
            field=models.CharField(blank='True', default='', max_length=256),
        ),
    ]
