# Generated by Django 3.2.25 on 2025-08-14 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0008_alter_questions_answer3_alter_questions_answer4'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('infant', 'Infant (0-2)'), ('toddler', 'Toddler (3-5)'), ('child', 'Child (6-12)'), ('teen', 'Teen (13-19)'), ('young_adult', 'Young Adult (20-29)'), ('adult', 'Adult (30+)')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('choice1_text', models.CharField(max_length=200)),
                ('choice1_science', models.IntegerField(default=0)),
                ('choice1_technology', models.IntegerField(default=0)),
                ('choice1_engineering', models.IntegerField(default=0)),
                ('choice1_math', models.IntegerField(default=0)),
                ('choice1_health', models.IntegerField(default=0)),
                ('choice1_intelligence', models.IntegerField(default=0)),
                ('choice1_creativity', models.IntegerField(default=0)),
                ('choice1_logic', models.IntegerField(default=0)),
                ('choice1_social', models.IntegerField(default=0)),
                ('choice2_text', models.CharField(max_length=200)),
                ('choice2_science', models.IntegerField(default=0)),
                ('choice2_technology', models.IntegerField(default=0)),
                ('choice2_engineering', models.IntegerField(default=0)),
                ('choice2_math', models.IntegerField(default=0)),
                ('choice2_health', models.IntegerField(default=0)),
                ('choice2_intelligence', models.IntegerField(default=0)),
                ('choice2_creativity', models.IntegerField(default=0)),
                ('choice2_logic', models.IntegerField(default=0)),
                ('choice2_social', models.IntegerField(default=0)),
                ('choice3_text', models.CharField(blank=True, max_length=200, null=True)),
                ('choice3_science', models.IntegerField(default=0)),
                ('choice3_technology', models.IntegerField(default=0)),
                ('choice3_engineering', models.IntegerField(default=0)),
                ('choice3_math', models.IntegerField(default=0)),
                ('choice3_health', models.IntegerField(default=0)),
                ('choice3_intelligence', models.IntegerField(default=0)),
                ('choice3_creativity', models.IntegerField(default=0)),
                ('choice3_logic', models.IntegerField(default=0)),
                ('choice3_social', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='creativity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='current_stage',
            field=models.CharField(default='infant', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='engineering_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='intelligence',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='logic',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='math_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='science_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='social_skills',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='technology_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='maker', to='stemlife.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_events', models.ManyToManyField(related_name='completed_by', to='stemlife.LifeEvent')),
                ('current_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stemlife.lifeevent')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemlife.player')),
            ],
        ),
    ]
