# Generated by Django 3.2.25 on 2025-08-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemlife', '0009_auto_20250814_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeevent',
            name='choice1_age_increment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='choice2_age_increment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='choice3_age_increment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once per stage'), ('multiple', 'Multiple times per stage'), ('rare', 'Rare event'), ('common', 'Common event')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='max_age',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifeevent',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('education', 'Education'), ('social', 'Social'), ('health', 'Health'), ('play', 'Play'), ('technology', 'Technology'), ('career', 'Career'), ('fun', 'Fun'), ('family', 'Family'), ('hobby', 'Hobby'), ('adventure', 'Adventure'), ('friendship', 'Friendship')], max_length=50),
        ),
    ]
